language: objective-c
before_install:
  - "brew update; brew uninstall xctool; brew install xctool"
  - "gem install cocoapods --no-rdoc --no-ri"
  - "cd PIXNET-iOS-SDK"
script: "xctool -workspace PIXNET-iOS-SDK.xcworkspace -scheme PIXNET-iOS-SDK -sdk iphonesimulator"
